### ISSUE TITLE
Metadata Rules button does not open window

### ISSUE THREAD

**Issue by kgrons** [avpreserve/mdqc#4]
Running MDQC 0.3 on Yosemite 10.10.5 with Tools > ExifTool preference selected.
- I load in a Reference File
- I click Metadata Rules button
- Nothing happens. I expect to see the metadata rules window show up so I can make further selections

I closed and re-opened MDQC, and then deleted and re-installed 3.0. Same result (no window)

Anybody else having this issue?

**Comment by clacinak** [comment]
@kgrons , are you still having this issue? I haven't heard about it from anyone else and am wondering if it was specific to your machine or if you have found this to persist in multiple instances.

**Comment by kgrons** [comment]
Hi @clacinak - multiple machines connected to the same storage array. I continued troubleshooting but was unable to resolve. Switched to MediaConch for policy checking. Will close this issue.
