### ISSUE TITLE
MDQC Python Error

### ISSUE THREAD

**Issue by iamdamosuzuki** [avpreserve/mdqc#5]
Initially the application could not find my Python Runtime. I was able to get it to see python by changing the Info.plist to include:

```
<dict>
    <key>PythonExecutable</key>
    <string>/usr/local/bin/python</string>
    <key>PythonLongVersion</key>
    <string>2.7.11 (default, Sep  9 2014, 15:04:36) GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)</string>
    <key>PythonShortVersion</key>
    <string>2.11</string>
    <key>py2app</key>
    <dict>
        <key>alias</key>
        <false/>
        <key>template</key>
        <string>app</string>
        <key>version</key>
        <string>0.8</string>
    </dict>
</dict>
```

However, now I get the follow traceback errors

3/28/16 1:22:03 PM  [0x0-0x35f35f].org.pythonmac.unspecified.MDQC[74871]    'import site' failed; use -v for traceback
3/28/16 1:22:03 PM  [0x0-0x35f35f].org.pythonmac.unspecified.MDQC[74871]    Traceback (most recent call last):
3/28/16 1:22:03 PM  [0x0-0x35f35f].org.pythonmac.unspecified.MDQC[74871]      File "/Applications/MDQC_0.3.app/Contents/Resources/**boot**.py", line 89, in <module>
3/28/16 1:22:03 PM  [0x0-0x35f35f].org.pythonmac.unspecified.MDQC[74871]        _run()
3/28/16 1:22:03 PM  [0x0-0x35f35f].org.pythonmac.unspecified.MDQC[74871]      File "/Applications/MDQC_0.3.app/Contents/Resources/__boot__.py", line 84, in _run
3/28/16 1:22:03 PM  [0x0-0x35f35f].org.pythonmac.unspecified.MDQC[74871]        exec(compile(source, path, 'exec'), globals(), globals())
3/28/16 1:22:03 PM  [0x0-0x35f35f].org.pythonmac.unspecified.MDQC[74871]      File "/Applications/MDQC_0.3.app/Contents/Resources/MDQC.py", line 7, in <module>
3/28/16 1:22:03 PM  [0x0-0x35f35f].org.pythonmac.unspecified.MDQC[74871]        from PySide.QtCore import *
3/28/16 1:22:03 PM  [0x0-0x35f35f].org.pythonmac.unspecified.MDQC[74871]    ImportError: No module named PySide.QtCore

I'm running Python 2.7.11, installed via Homebrew, on a mac with OS X 10.6.8

Thanks!
MoMo

**Comment by smntb** [comment]
The application will only work with OS X >=10.8 because it is compiled with the OS binaries. You need to upgrade your OS to successfully run the application
