### ISSUE TITLE
Menu missing on Mac version

### ISSUE THREAD

**Issue by micasey** [avpreserve/mdqc#7]
The File and Tools menus are not present in the Mac version of the application. They are present in the Windows version.

**Comment by clacinak** [comment]
Hi Mike,

They are in a different place on the Mac OS than on the Windows OS. See the attached image and look in the upper left. Do you see something different on yours? If so, please send along a screen grab and let us know what OS and version of MDQC you are using.

Thanks,

Chris

![mdqc menus mac](https://user-images.githubusercontent.com/2552814/28292171-22017b16-6b0b-11e7-9bf1-7f4acf618e7f.png)
